### ISSUE TITLE
Package as .deb for raspberry pi

### ISSUE THREAD

**Issue by euforic** [hcw70/OpenNI2#11]
Sorry for the noobs question, but how would I do I generate the .deb file to install on raspberry pi?

**Comment by hcw70** [comment]
Login to your pi.

git clone  https://github.com/hcw70/OpenNI2
cd OpenNi2
git checkout debian-master
git-buildpackage --git-no-sign-tags --git-ignore-new -us -uc 
cd ..
sudo dpkg -i *.deb

Kind regards
Hauke

**Comment by drebelox** [comment]
I am having an problem with generating the debian package. I get this error:

```
Now signing dsc file...
 signfile openni2_2.1.0.4-1ubuntu1~1.gbp2a4158.dsc Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
gpg: skipped "Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>": secret key not available
gpg: /tmp/debsign.G1R7pZIE/openni2_2.1.0.4-1ubuntu1~1.gbp2a4158.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1288:
running debsign failed
gbp:error: Couldn't run 'debuild -i -I -uc': debuild -i -I returned 29
```

Thank you for the help!

**Comment by hcw70** [comment]
@drebelox That is what the flag "-us" in the above hint is for: Skip signing.

**Comment by drebelox** [comment]
Thank you... I was running it just like the hint but still got that error. So I removed everything and tried again and it worked.

**Comment by hcw70** [comment]
I have added a hint in the description for my branched repo. Hope this helps.
