### ISSUE TITLE
Cannot find device driver libraries

### ISSUE THREAD

**Issue by jonbinney** [hcw70/OpenNI2#12]
This seems to be because the libopenni2-0 library puts the libraries for each device driver in /usr/lib/OpenNI2/Drivers, but doesn't add that to the library search path in /etc/ld.so.conf. 

This problem can cause the openni2_camera package to fail as described here: https://github.com/ros-drivers/openni2_camera/issues/10

It appears that when loading the device-specific libraries, OpenNI2 first changes to the directory where they live:

https://github.com/hcw70/OpenNI2/blob/debian-master/Source/Core/OniContext.cpp#L184-L188

But for some reason it still doesn't find the libraries when it is run.

**Comment by jonbinney** [comment]
According to the documentation for dlopen, it "If filename contains a slash ("/"), then it is interpreted as a (relative or absolute) pathname.". So maybe all that is needed is to prepend the library name with "./" so that it searches the current directory?

**Comment by jspricke** [comment]
Yeah, adding the absolute path sounds like good solution.

**Comment by hcw70** [comment]
Hmm. I am unsure why this happens in the first place. I had a working openni2_camera (ubuntu + Raspi) running a few weeks ago. And shouldnt be specifying libopenni2.pc via pkg-config be enough when linking client code?

**Comment by jonbinney** [comment]
Were you using openni2_camera from source? When you run it from catkin's devel space, it adds the library directories it got from pkg-config to LD_LIBRARY_PATH, so this works fine. But once you install it (for example doing a catkin_make install or once we release a debian of it), the pkg-config library paths aren't used anymore. If OpenNI2 wants to install libraries to a non-standard place, then it either needs to load them using a full path, or add something to /etc/ld.so.conf.d/ so that the libraries can be found.

I'm not sure I understand exactly what is happening here though. I tried compiling OpenNI2 from source, and copying the resulting libOpenNI2.so over the one that came in the debian, and I no longer had the problem (it appears to load the driver libraries fine). So I'm still trying to reproduce this from source. What commands do I need to run to generate a deb file from the OpenNI2 sources?

**Comment by hcw70** [comment]
I did use openni2_camera from source and ran it from catkins devel space.

To generate a debian package:
https://github.com/hcw70/OpenNI2/wiki

**Comment by jonbinney** [comment]
Thanks, I'll try to recreate this problem with generated debians.

To see the problem, you have to be using openni2_camera in install space. If you're curious, there's instructions to recreate the problem here: https://github.com/ros-drivers/openni2_camera/issues/10

**Comment by bit-pirate** [comment]
Are there any updates on this? Just ran into the same problem while working on the openni2_tracker.

**Comment by hcw70** [comment]
I will have a look at this in the next few days.

**Comment by wjwwood** [comment]
You can override where it looks using an environment variable, for instance this works for me:

```
OPENNI2_DRIVERS_PATH=/usr/local/Cellar/openni2/2.1.0.4/lib/OpenNI2/Drivers roslaunch openni2_launch openni2.launch
```

It looks like you can also do this within the openni2 config files. That might be the best way to do it.

**Comment by mikeferguson** [comment]
I've been messing around with this today and have a patch based that will fix this, by backporting a patch that was made to libopenni's linux xn shared library loader after our branch was made.

@jspricke I presume ROS is using your PPA for the deb, is that right? If so, where are you building your source deb out of, and where should I submit patches for libopenni?

**Comment by jspricke** [comment]
- Michael Ferguson notifications@github.com [2013-08-19 23:50]:
  > I've been messing around with this today and have a patch based that will fix this, by backporting a patch that was made to libopenni's linux xn shared library loader after our branch was made.

Sounds good. Also, we should start integrating the new upstream
versions. @hcw70 are you working on tnis?

> @jspricke I presume ROS is using your PPA for the deb, is that right? If so, where are you building your source deb out of, and where should I submit patches for libopenni?

I'm using this repo, so go ahead and send a pull request.

Cheers Jochen

**Comment by mikeferguson** [comment]
@jspricke Thanks, will open a PR tomorrow morning when I get back into the office.

As for integrating the 2.2 branch of upstream, I'd like to get one reliable version of this 2.1 chain pushed all the way through debs, so that we can get openni2_camera released, for some reason the old "install a copy of the newer Openni1.5.4 over the top of your debs" has stopped working for me with the newer 1.082 and 1.09 Primesense Sensors, but openni2_camera works great.

**Comment by bit-pirate** [comment]
> for some reason the old "install a copy of the newer Openni1.5.4 over the
> top of your debs" has stopped working for me with the newer 1.082 and 1.09
> Primesense Sensors, but openni2_camera works great.
> 
> That's not only you. Must be some driver problem of the old OpenNi.

**Comment by mikeferguson** [comment]
@bit-pirate I tried on multiple computers, and all I get is segfaults now, so I figure something has changed somewhere such that we no longer have ABI and all hell breaks loose. Either way, the openni2 stuff is the way to go, and with the pull request I opened a few minutes ago, we should be able to actually release the openni2_camera stuff shortly.
