### ISSUE TITLE
Glitch in pkg-config file

### ISSUE THREAD

**Issue by marlam** [hcw70/OpenNI2#13]
Hi,

the pkg-config file lists "-lPS1080.so" in the required libs (at least in the Ubuntu 13.04 package as distributed from the PPA of Jochen Sprickerhof). That library does not exist on this system. It seems the entry can simply be removed(?)

Martin

**Comment by hcw70** [comment]
Sorry for the late feedback. 

That lib is there in my system and is really needed. It contains the driver code for the Xtion device.

It is actually in package libopenni2-dev.
