### ISSUE TITLE
Doesn't compile on Ubuntu x86

### ISSUE THREAD

**Issue by jamesdebono** [hcw70/OpenNI2#15]
Using Lubuntu x86 to compile the development.
This error is generated:
g++ -o ../../../Bin/x86-Release/libOpenNI2.jni.so ./../../../Bin/Intermediate/x86-Release/libOpenNI2.jni.so/OpenNI.jni.o ./../../../Bin/Intermediate/x86-Release/libOpenNI2.jni.so/org_openni_android_OpenNIView.o ./../../../Bin/Intermediate/x86-Release/libOpenNI2.jni.so/org_openni_NativeMethods.o  -L../../../Bin/x86-Release -lOpenNI2 -Wl,--no-undefined -shared
/usr/lib/i386-linux-gnu/libc_nonshared.a(stack_chk_fail_local.oS): In function `__stack_chk_fail_local':
(.text+0x10): undefined reference to`__stack_chk_fail'
collect2: error: ld returned 1 exit status
make[1]: **\* [../../../Bin/x86-Release/libOpenNI2.jni.so] Error 1
make[1]: Leaving directory `/home/james/Downloads/OpenNI2-debian-develop/Wrappers/java/jni'
make: **\* [Wrappers/java/jni] Error 2

**Comment by hcw70** [comment]
Sorry for the late answer. Please report this issue upstream. I think i have seen it there already.
