### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by migherault** [hcw70/OpenNI2#19]
Dear all,
I've been trying to compile and install OpenNI2 on my RaspBerry PI modèle B+ including ARM1176JZF-S core for 3 days, and I cannot fix problems.
Here is what I did in details:
    \* sudo apt-get install git g++ python libusb-1.0-0-dev freeglut3-dev openjdk-6-jdk graphviz
    \* sudo apt-get install libudev-dev
keep OpenNI2
    \* https://github.com/kalectro/OpenNI2.git
Uncompress OpenNI2-gumstix-fixes.zip on Rasp and check the CRC
    *CRC is good: 56cc12233eed6aea9efe9f64254d507e183dbef4

___ 1 ____________________________________________________________________
In OpenNI2-Master/ThirdParty/PSCommon/BuildSystem modifying 
    *CFLAGS +=  -mtune=arm1176jzf-s -mfloat-abi=hard

___ 2 _____________________________________________________________________
The second file is OpenNI2/Redist/Redist.py. Go to line 534 to find this:
    \* compilation_cmd = "make -j" + calc_jobs_number() + " CFG=" + configuration + " PLATFORM=" + platform + " > " + outfile + " 2>&1"
Then duplicate the line, comment the original and change the copied line:
    \* compilation_cmd = "make -j1" + " CFG=" + configuration + " PLATFORM=" + platform + " > " + outfile + " 2>&1"

___ 3 ____________________________________________________________________

```
* cd OpenNI2-gumstix-fixes
* make
```

Till there evrything seems to be ok.
Compilation took arround 20 min as it is used to be said over the Internet.
___ 4 ____________________________________________________________________
cd ..
cd Redist
sudo python ReleaseVersion.py arm

!!!!!!!!!!!!!!!!!!
and there things goes wrong here is the coplete prompt of the terminal:

sudo python ReleaseVersion.py arm
Path: ..
Output: /home/pi/OpenNI2-gumstix-fixes/Redist/OpenNI-2.1.0-arm
Platform: arm
Compile: Build
Docs: True
Tools: False
make -j1 CFG=Release PLATFORM=Arm > /home/pi/OpenNI2-gumstix-fixes/Redist/build.Release.Arm.txt 2>&1
RC: 512
Compilation failure

!!!!!!!!!!!!!!!!

Please help me! What can I do?

**Comment by hcw70** [comment]
Since you cloned from https://github.com/kalectro/OpenNI2.git which has something like "gumstix-fixes", either direct the issue to that guy or use my version. 

My version is known to compile on ubuntu and debian on Raspi.

Regards
Hauke

**Comment by migherault** [comment]
Many thanks for your answer, I did it but there is no the Redist Folder and I didn't manage to go further.
I finally found the solution by modifying the "commondef" file by commenting line 27 to 41 and hading line 42: PLATFORM = $(HOST_PLATFORM)

and it compile.

Thanks again,
Mig

**Comment by hcw70** [comment]
Ok to close the issue?

**Comment by migherault** [comment]
Yes of course!
