### ISSUE TITLE
Cross-Compiling for arm on Linux

### ISSUE THREAD

**Issue by Kumrai-T** [hcw70/OpenNI2#20]
Could you please give more details of this part?
   Cross-Compiling for ARM on Linux:
     The following environment variables should be defined:
     - ARM_CXX=<path to cross-compilation g++>
     - ARM_STAGING=<path to cross-compilation staging dir>

How could I do for getting "<path to cross-compilation g++>" and "<path to cross-compilation staging dir>"?

Thanks, Kumrai

**Comment by hcw70** [comment]
Sorry i cant help you here. 
Pls consult upstream maintainer or try google.
